[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "extension_helpers",
            "wheel"]

build-backend = 'setuptools.build_meta'

[tool.autopep8]
max_line_length = 100
in-place = true
recursive = true

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

known_third_party = ["astropy", "erfa", "extension_helpers", "filterpy", "galpy", "matplotlib", "numpy", "pytest", "scipy", "setuptools", "streamtools", "typing_extensions"]
known_localfolder = "trackstream"

import_heading_stdlib = "STDLIB"
import_heading_thirdparty = "THIRD PARTY"
import_heading_firstparty = "FIRST PARTY"
import_heading_localfolder = "LOCAL"


[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
